### ISSUE TITLE
Thanks for this module

### ISSUE THREAD

**Issue by pizzadude** [leewp14/xposed.leewp14.NEClient#1]
I don't speak chinese because I am from canada but....

Thanks for this module. It seems to be working fine on Lineage OS 14.1 (android nougat 7.1) with the xposed unofficial for nougat 7.1 (magisk module).

Some songs I can't play, don't know what that was about as I don't speak chinese but thanks for making the module so I can listen in canada!

**Comment by leewp14** [comment]
Glad it works with xposed magisk. 
Thank you for your feedback! Currently due to some server side changes (API) on netease and various music providers' server, i estimate that there should be about 2-10% of paid songs not able to be bypassed due to imperfection of the code, which most of them are newly released tracks. You will get error 资源不存在for this problem. But do be noted that some 资源不存在 is due to missing of resource, not due to unsuccessful bypass. 
I will keep this app updated with bin456789's as mine includes english translation for the module which might benefits many people out there. Do check my repo regularly to get latest release!

**Comment by pizzadude** [comment]
Thank you for your explanation! :D

**Comment by pizzadude** [comment]
This module also works in official Xposed for Nougat. 

I also used the module "AllTrans" to translate Netease Music to English.

**Comment by leewp14** [comment]
Thanks for reporting. I've also tried on my phone (nougat) recently. Looks like the only problem now is to get the api code to be fixed. I have no kNowledge about how netease new api works so literally there's nothing I can do unfortunately. We can only wait for bin456789 to fix this problem, seems like he's the only one to understand the special netease api he use (xmusic.xmusic.top)
