### ISSUE TITLE
Sometimes the module prevent me from doing activities in NetEase Music

### ISSUE THREAD

**Issue by tensaigandy** [leewp14/xposed.leewp14.NEClient#4]
Title, like streaming the music, browsing my inbox, and browsing artists/title/album. But the download seems fine.

E: I also using AdAway and add some lines from my pastebin to unblock some sites like Reddit, music.163.com and things. Do you think it clashed with your module?

**Comment by leewp14** [comment]
There should be some difficulties to play some songs, but other functions should work fine. It could be your AdAway blocking those features (inbox, browse). I also use AdAway without custom lines and my sis also using this module but no AdAway on her phone and so far NetEase works fine on both of our device for those functions. 

We need to wait until someone figures out how the new NetEase API works in order to get full music stream functionality (as for now some songs won't be able to play). So far there have been no updates, you may keep an eye on bin456789's unblock163musicclient-xposed which is base of this module (this module is created just to add English Translation to the original one) and some minor improvements. 

Do give the AdAway thingy a try by remove your music.163.com line, and report back if possible :smile: 
Thanks.

**Comment by tensaigandy** [comment]
It would be the issue. I removed my AdAway and there's no error notification on my NetEase Client. Probably it was caused by my tons of 163.com lines in my hosts file. I'll try to remove them later and will update it here.

**Comment by tensaigandy** [comment]
Update:

So after applying this module, **I need to remove all 163.com and 126.net lines from my hosts file**. I even can play Eminem song now. Thanks for the module man! Really appreciate it.

**Comment by leewp14** [comment]
Glad it works now. Thanks for reporting. :smile:
